package com.example.djeventhub.ui.addevent

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.example.djeventhub.Event
import com.example.djeventhub.EventRepository
import com.example.djeventhub.location.LocationManager
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch

sealed class AddEventUiState {
    object Idle : AddEventUiState()
    object Loading : AddEventUiState()
    data class LocationCaptured(val lat: Double, val lng: Double) : AddEventUiState()
    object Success : AddEventUiState()
    data class Error(val message: String) : AddEventUiState()
}

class AddEventViewModel(application: Application) : AndroidViewModel(application) {
    private val repository = EventRepository
    private val locationManager = LocationManager(application.applicationContext)

    private val _uiState = MutableStateFlow<AddEventUiState>(AddEventUiState.Idle)
    val uiState: StateFlow<AddEventUiState> = _uiState

    private var capturedLatitude: Double? = null
    private var capturedLongitude: Double? = null

    fun useCurrentLocation() {
        viewModelScope.launch {
            _uiState.value = AddEventUiState.Loading
            try {
                val location = locationManager.getCurrentLocation()
                if (location != null) {
                    capturedLatitude = location.latitude
                    capturedLongitude = location.longitude
                    _uiState.value = AddEventUiState.LocationCaptured(
                        lat = location.latitude,
                        lng = location.longitude
                    )
                } else {
                    _uiState.value = AddEventUiState.Error("No se pudo obtener la ubicación")
                }
            } catch (e: Exception) {
                _uiState.value = AddEventUiState.Error("Error al obtener ubicación: ${e.message}")
            }
        }
    }

    fun createEvent(
        name: String,
        description: String,
        locationName: String,
        date: Long,
        latitude: Double?,
        longitude: Double?
    ) {
        if (name.isBlank() || description.isBlank()) {
            _uiState.value = AddEventUiState.Error("El nombre y descripción son obligatorios")
            return
        }

        viewModelScope.launch {
            _uiState.value = AddEventUiState.Loading
            try {
                val newEvent = Event(
                    id = "", // Will be generated by repository
                    name = name,
                    description = description,
                    date = date,
                    locationName = locationName,
                    latitude = latitude,
                    longitude = longitude,
                    imageUrl = null
                )

                repository.addEvent(newEvent)
                _uiState.value = AddEventUiState.Success
            } catch (e: Exception) {
                _uiState.value = AddEventUiState.Error("Error al crear evento: ${e.message}")
            }
        }
    }
}
