package com.example.djeventhub.ui.addevent

import android.app.Application
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.example.djeventhub.data.EventRepository
import com.example.djeventhub.data.StorageRepository
import com.example.djeventhub.models.Event
import com.example.djeventhub.location.LocationManager
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.launch
import javax.inject.Inject

sealed class AddEventUiState {
    object Idle : AddEventUiState()
    object Loading : AddEventUiState()
    data class Uploading(val progress: Float) : AddEventUiState()
    data class LocationCaptured(val lat: Double, val lng: Double) : AddEventUiState()
    object Success : AddEventUiState()
    data class Error(val message: String) : AddEventUiState()
}

@HiltViewModel
class AddEventViewModel @Inject constructor(
    application: Application,
    private val repository: EventRepository,
    private val storageRepository: StorageRepository,
    private val locationManager: LocationManager
) : AndroidViewModel(application) {

    private val _uiState = MutableStateFlow<AddEventUiState>(AddEventUiState.Idle)
    val uiState: StateFlow<AddEventUiState> = _uiState

    private var capturedLatitude: Double? = null
    private var capturedLongitude: Double? = null

    fun useCurrentLocation() {
        viewModelScope.launch {
            _uiState.value = AddEventUiState.Loading
            try {
                val location = locationManager.getCurrentLocation()
                if (location != null) {
                    capturedLatitude = location.latitude
                    capturedLongitude = location.longitude
                    _uiState.value = AddEventUiState.LocationCaptured(
                        lat = location.latitude,
                        lng = location.longitude
                    )
                } else {
                    _uiState.value = AddEventUiState.Error("No se pudo obtener la ubicación")
                }
            } catch (e: Exception) {
                _uiState.value = AddEventUiState.Error("Error al obtener ubicación: ${e.message}")
            }
        }
    }

    fun createEvent(
        name: String,
        description: String,
        locationName: String,
        startDate: Long,
        endDate: Long?,
        latitude: Double?,
        longitude: Double?,
        musicGenre: String?,
        imageUri: android.net.Uri?
    ) {
        if (name.isBlank() || description.isBlank()) {
            _uiState.value = AddEventUiState.Error("El nombre y descripción son obligatorios")
            return
        }

        viewModelScope.launch {
            _uiState.value = AddEventUiState.Loading
            try {
                // Upload image to Firebase Storage if provided
                var imageUrl: String? = null
                if (imageUri != null) {
                    val uploadResult = storageRepository.uploadEventImageWithProgress(imageUri) { progress ->
                        _uiState.value = AddEventUiState.Uploading(progress)
                    }

                    uploadResult.fold(
                        onSuccess = { url ->
                            imageUrl = url
                        },
                        onFailure = { exception ->
                            _uiState.value = AddEventUiState.Error("Error al subir imagen: ${exception.message}")
                            return@launch
                        }
                    )
                }

                // Create event with uploaded image URL
                _uiState.value = AddEventUiState.Loading
                val newEvent = Event(
                    id = "", // Will be generated by repository
                    name = name,
                    description = description,
                    date = startDate,
                    endDate = endDate,
                    locationName = locationName,
                    latitude = latitude,
                    longitude = longitude,
                    imageUrl = imageUrl,
                    musicGenre = if (musicGenre.isNullOrBlank()) null else musicGenre
                )

                val result = repository.addEvent(newEvent)
                result.fold(
                    onSuccess = { eventId ->
                        _uiState.value = AddEventUiState.Success
                    },
                    onFailure = { exception ->
                        _uiState.value = AddEventUiState.Error("Error al crear evento: ${exception.message}")
                    }
                )
            } catch (e: Exception) {
                _uiState.value = AddEventUiState.Error("Error al crear evento: ${e.message}")
            }
        }
    }
}
